apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.26.92  # NFS server IP
    path: /index_dir
  persistentVolumeReclaimPolicy: Retain

